### ISSUE TITLE
CEU pin definition

### ISSUE THREAD

**Issue by Florianbbbb** [d-kato/mbed-gr-libs#1]
Hi,

There is an issue when I execute openCV sample for GRlychee with this library. 
When I call the function drv_graphics_error_t DRV_Graphics_CEU_Port_Init. 
The function pinmap serial return the error :
MBED_MODULE_PLATFORM, MBED_ERROR_CODE_PINMAP_INVALID), "pinmap not found for peripheral"

**Comment by d-kato** [comment]
@Florianbbbb, Normally, GR-LYCHEE does not use CEU. I think that the definition of CAMERA_MODULE is not set correctly. Please check if "EasyAttach_CameraAndLCD.h" is up to date.
I confirmed that it works normally with [this sample](https://github.com/d-kato/GR-Boards_OpenCV_sample).

**Comment by Florianbbbb** [comment]
I will check today. Just to be clear. In your code, you redefine the CAM pin to use the ceu driver  through the pin of Cam connector ( CN12 on lychee ) ?

**Comment by d-kato** [comment]
I do not redefine the CAM pin. The pin of CN12 is for VDC5. It can not be used in the CEU. Therefore, MODULE_VDC must be set in CAMERA_MODULE.

Please refer to the following.
* [EasyAttach_CameraAndLCD.h](https://github.com/d-kato/mbed-gr-libs/blob/master/EasyAttach_CameraAndLCD/EasyAttach_CameraAndLCD.h#L24).
* [EasyAttach_CameraAndLCD.cpp](https://github.com/d-kato/mbed-gr-libs/blob/master/EasyAttach_CameraAndLCD/EasyAttach_CameraAndLCD.cpp#L121-L128)

**Comment by Florianbbbb** [comment]
Ok thank you. So I can't use ceu driver with GRlychee and camera connector  ? 
Because I would like to use ov7740 which use only ceu driver with GRlychee

**Comment by d-kato** [comment]
GR-LYCHEE can not use CEU. On the RZ/A1LU chip, the CEU uses the [these pins](https://github.com/d-kato/mbed-gr-libs/blob/master/GR-PEACH_video/targets/TARGET_RZ_A1XX/TARGET_RZA1UL/gr_lychee_vdc5.c#L85-L98). In GR-LYCHEE, these pins are used for different purposes.

**Comment by Florianbbbb** [comment]
It's not possible to change pin input of CEU driver ?

**Comment by d-kato** [comment]
It is hard specification and can not be changed. Please see [here](http://www.renesas.com/products/mpumcu/rz/rza/rza1lu/index.jsp) for the detail.
By the way, in case of GR-PEACH, VDC 5 and CEU pins are the same, so it can operate with CUE. When used in combination with the [GR-PEACH Wireless CAMERA shield](https://www.core.co.jp/product/m2m/gr-peach/audio-camera.html), it will be similar to GR-LYCHEE.

**Comment by Florianbbbb** [comment]
thanks you for your help. 
Unfortunately, I haven't GR-Peach.
I will check you driver with my stream it 2 éval  board.

**Comment by d-kato** [comment]
Please be careful. In OV7740, the order of pins may be reversed to CN12 of GR-LYCHEE.

**Comment by Florianbbbb** [comment]
So, I can't connect the ov7740 on lychee. 
I must reversed the cmos_camera_pin definition  on easy_attach file ?

**Comment by d-kato** [comment]
Since GR-LYCHEE can not use CEU, please restore the setting.
